server:
  port: 8080
spring:
  thymeleaf:
    cache: false

dubbo:
  application:
    name: customer-web
  registry:
    address: zookeeper://192.168.118.168:2181
  consumer:
    check: false
    timeout: 15000
